title: Alexander Gurevich - Products Portfolio
logo: /assets/BusinessCard.png
#description: text below image
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
show_downloads: false
# theme: jekyll-theme-minimal
github_hide: true
